numpy:
  # part of a zip_keys: python, python_impl, numpy
  - 1.18
    #- 1.22
    #- 1.22
    #- 1.22
    #- 1.23
python:
  # part of a zip_keys: python, python_impl, numpy
  - 3.7.*
    #- 3.8.*
    #- 3.9.*
    #- 3.10.*
    #- 3.11.*

zip_keys:
  -
    - python
    - numpy
