package:
  name: pygeode
  version: "{{ environ['VERSION'] }}"

source:
  git_rev: "{{ environ['VERSION_TAG'] }}"
  git_url: https://github.com/pygeode/pygeode.git

requirements:
  build:
    - python
    - setuptools
    - netcdf4
    - numpy
    - scipy
    - matplotlib
    - progressbar2
    - gsl

  run:
    - python
    - netcdf4
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib
    - progressbar2
    - gsl

test:
  # Python imports
  imports:
    - pygeode

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - nose

about:
  home: http://pygeode.github.io/ 
  license: GPL3
  license_file: LICENSE
  summary: "A Python package for dealing with large gridded datasets"

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
