name: Build and Publish PyPI wheel

on: 
  workflow_dispatch:
  release:

jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
    defaults:
      run:
        shell: bash -el {0}

    steps:
     - name: Checkout Repository
       uses: actions/checkout@v4

     - name: Build wheels
       uses: pypa/cibuildwheel@v2.16.0
       env:
         CIBW_BEFORE_ALL: >-
           yum install -y atlas-devel lapack-devel gsl-devel netcdf hdf5
         CIBW_BEFORE_BUILD: >-
           pip install numpy scipy matplotlib netcdf4 progressbar2
         CIBW_BUILD: >-
           cp3{8,9,10,11}-manylinux_x86_64
         #CIBW_SKIP: >-
           #cp312-*
           #pp*
           #*_i686
           # Dependencies aren't yet working for CPython 3.12 or for the PyPy wheels (HDF5?)
           # The i686 builds fail on the yum install as they can't find netcdf; the 
       with:
         output-dir: wheelhouse

     - name: Upload Wheels
       uses: actions/upload-artifact@v3
       with:
         name: wheels
         path: ./wheelhouse/*.whl

  publish-to-testpypi:
    name: Publish wheels to TestPyPI
    needs:
    - build-wheels
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/pygeode

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: wheels
        path: dist/

    - name: Publish distribution to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

